### ISSUE TITLE
Not Discovering Devices

### ISSUE THREAD

**Issue by Abrajkovic** [kate-hall/alexa-icomfort#15]
I was able to complete the full process and enabled the skill, however, Alexa is not discovering the devices.    Confirmed that the login id / password are correct and comfort wifi thermostat is working fine.  No error messages of any kind, just no device names for the icomfort thermostat after discovery completes.  I disabled and enabled the skill, but still no discovery of the device names.  

Any ideas on how to troubleshoot?

**Comment by BWilkey** [comment]
I am having the same problem and haven't been able to get Alexa to discover my thermostat.  The only area I'm not sure I have done right is the Lambda function role.  Since this was my first Alexa skill, I had to create a role.  I don't know which policies the role should include.  I've tried a few that include "discovery" in their names:  AWSAgentlessDiscoveryService, AWSApplicationDiscoveryAgentAccess, and AWSApplicationDiscoveryServiceFullAccess.  But I still can't get Alexa to discover my thermostat.

**Comment by BWilkey** [comment]
I got it working!  I started over with the Lambda Function, making sure that when I selected the Blueprint (first step in Lambda function creation), that I used the "Select Runtime" dropdown menu to limit the search to ONLY Node.js 4.3.  Then I searched for "alexa-smart-home-skill-adapter".  This, apparently gets the process started with the correct runtime for the code provided in this GitHub.  For the lambda_basic_execution role, I made sure the policies attached were "CloudWatchLogsFullAccess" and "AWSLambdaBasicExecutionRole".  I also went to the Releases page here (https://github.com/kate-hall/alexa-icomfort/releases) and used the source code (.zip) file instead of the one in the Wiki instructions page. I think this one has the very latest capabilities offered.  Otherwise, I did what the Wiki instructions said to do, and I'm now controlling my iComfort Wi-Fi thermostat by voice!   Thanks, Kate, for putting this out here!

**Comment by Abrajkovic** [comment]
Brian - thanks for the tips - its working for me now too!

Kate - thanks for setting this all up.

**Comment by manuelpalacios** [comment]
Hi there, 

First thank you for developing this skill Kate. Second, I am having this same issue. I went back and repeat it the installation using the last version. From Brian's suggestion the I couldn't figure out how to make sure that "the policies attached were "CloudWatchLogsFullAccess" and "AWSLambdaBasicExecutionRole"". Everything else seems to be working fine, but it is just the discovery of the thermostat where it fails. 

Thanks in advance for any help!

**Comment by Abrajkovic** [comment]
You can do that through the AWS Console:
https://console.aws.amazon.com/console/home?region=us-east-1
Select the IAM Service
Select Roles from Left side of screen menu
Edit lambda_basic_execution role and add the policies

**Comment by manuelpalacios** [comment]
Thanks a lot for the reply. 

My Alexa App is still not discovering the thermostat :( 

I might be doing something else wrong. I did add the policies. 
![image](https://user-images.githubusercontent.com/30837924/29087331-9a2dc704-7c43-11e7-8a0d-2aeeed5b5114.png)

Is there anything else you guys can think of? I know this is not meant for trouble shooting, but I would really appreciate any addition help 

![image](https://user-images.githubusercontent.com/30837924/29087500-3043ee30-7c44-11e7-9231-be71004d1843.png)

**Comment by BWilkey** [comment]
I'm not sure I can help, but here are a couple of thoughts:  1) Having "Node.js 4.3" selected for Runtime seems to be critical, so double check that, 2) I do not have any Inline Policies, I don't know if yours might be an issue, and 3) I do have a third Managed Policy, but I don't know if it is making a difference for me.  My third Managed Policy is a version of the AWSLambdaBasicExecutionRole with resource specified.  I'll attach the screenshot below.  I don't want to remove it to see if it affects my skill in case I can't get it to work again!  :)  

![screen shot iam mgt console](https://user-images.githubusercontent.com/18273549/29136291-c30c11d6-7d0a-11e7-89d7-de99830421c4.png)
![screen shot iam policy details](https://user-images.githubusercontent.com/18273549/29136290-c3030046-7d0a-11e7-9707-c5982f83cd01.png)

**Comment by meadandale** [comment]
I'm having the same problem as the others. I've gone through the whole setup process and the authentication with myicomfort is working but I'm not seeing any device.

Edit: I got this working. I was using the wrong username.

Now the problem I'm having is that it's not setting the temp correctly. I say "Computer, set Thermostat to 74". It repeats the command but the thermostat gets set to a different value (e.g. 77).

**Comment by smahaffey** [comment]
Kate thank you so much for this.  This was very easy and it will be very useful.

I also had trouble with discovery initially and found that it worked perfectly after I had followed the steps from Brian(Thank you) and then changed the payload version to v2(legacy) from v3 (preferred) in the Smart Home Skill setup in the Developer Portal.  I suspect this payload version is something that has changed more recently.

**Comment by yungwesl** [comment]
Kate this is A-M-A-Z-I-N-G!

Also confirming Smahaffey's comment.  From your instructions there only needs to be TWO deviations:
1. Add the policies Brian mentioned
2. Change the payload to v2 (from v3).  
I'm using it in Celcius and it's funny by apparently my iComfort is providing the current temperature as 21.11111111C so Alexa reads the entire string.  I'll try to hack my copy to cut off the decimals and round to the nearest 0.5C

Wes

**Comment by rmelody** [comment]
I am unable to change the payload back to v2 and only v3 are available.  Has anyone else run into this?

**Comment by yungwesl** [comment]
I went back into my Alexa dashboard and I can still see v2 and v3 offered as payload options.  I am running out of the server in developer.amazon.com

**Comment by briless** [comment]
I also cannot create a new v2 skill.  Looks like v2 is completely deprecated for any new skill creation.  Once you change an existing skill to v3 you cannot go back either.  Seems this skill might need an update to v3 or see if there's a workaround to creating a v2 skill.

**Comment by StarfighterJ** [comment]
Help I also had trouble with discovery tried to do another Create Skill but it will not let me select v2 only v3 is Avaible. Also under endpoint What Goes in Default ? As of right now I use the ARN there and under North America. I am new at this but how can I see what is in the LambdaBasicExecution. any help would be appreciated Thnkyou
