### ISSUE TITLE
Add Echo show product support

### ISSUE THREAD

**Issue by seattledesign** [kate-hall/alexa-icomfort#24]
Would be great to enable the Show Ui.

**Comment by kate-hall** [comment]
I would LOVE to, but I believe the display interface capabilities are only accessible within custom skills, not Smart Home Skills...at least, that's the only place the Alexa Skills Kit documents those capabilities. See here: https://developer.amazon.com/docs/custom-skills/create-skill-with-screen-display.html 

The Smart Home Skill capability is really locked down, unfortunately. I have several Smart Home devices (mostly lights and smart plugs) and an Echo Show, and I just tested lots of different commands for all of them, none of them bring up a display, and I'm often directed to the Alexa App for more control.

Note that there's currently a bug in the Alexa App display of the iComfort (it shows `[object object` instead of control buttons), I've got a ticket open with Amazon right now to sort it out.
